import os
import numpy as np
import matplotlib.pyplot as plt
import scipy.constants as spc

os.system("./bin/OpacityTests")
refValues=np.genfromtxt("./ReferenceValues/reference_data.csv",delimiter=",")
refValue_dusts=np.genfromtxt("./ReferenceValues/reference_data_dust.csv",delimiter=",")
refValue_dustsize=np.genfromtxt("./ReferenceValues/reference_data_dust_s.csv",delimiter=",")
resultsKappa=np.fromfile("./bin/KDust.bin",dtype="double")
#resultsKappa = np.genfromtxt("./bin/KDust.csv",delimiter=" ")
resultsHj = np.genfromtxt("./bin/HDust.csv",delimiter=" ")
resultsXj = np.genfromtxt("./bin/XDust.csv",delimiter=" ")
resultsSigma = np.genfromtxt("./bin/SigmaDust.csv",delimiter=" ")
resultsE1 = np.genfromtxt("./bin/E1Dust.csv",delimiter=" ")
resultsE2 = np.genfromtxt("./bin/E2Dust.csv",delimiter=" ")
refValue_Hj=np.genfromtxt("./ReferenceValues/reference_data_Hj.csv",delimiter=",")
refValue_Xj=np.genfromtxt("./ReferenceValues/reference_data_Xj.csv",delimiter=",")
refValue_Sigma=np.genfromtxt("./ReferenceValues/reference_data_sig.csv",delimiter=",")
refValue_E1=np.genfromtxt("./ReferenceValues/reference_data_e1.csv",delimiter=",")
refValue_E2=np.genfromtxt("./ReferenceValues/reference_data_e2.csv",delimiter=",")
resultsLambda = np.genfromtxt("./bin/Lambda.csv",delimiter=" ")
resultsDust = np.genfromtxt("./bin/Dust.csv",delimiter=" ")
resultsDustSize = np.genfromtxt("./bin/Dust_size.csv",delimiter=" ")
tpe = np.dtype([('i','<i2'), ('q','<i2')])
resultsNu = np.genfromtxt("./bin/EffectiveConductivities.csv",delimiter=" ")
resultsNu = np.asarray([np.complex(arV[0],arV[1]) for arV in resultsNu])
refValues_nu = np.loadtxt("./ReferenceValues/reference_data_nu.csv").view(complex)

""" #print(resultsNu)
plt.figure()
plt.loglog(refValues[:,0],refValue_Hj)
plt.loglog((spc.speed_of_light*1e2)/(resultsLambda),resultsHj)
plt.show()
plt.figure()
plt.loglog(refValues[:,0],refValue_Xj,label="py")
plt.loglog((spc.speed_of_light*1e2)/(resultsLambda),resultsXj,label="C++")
plt.legend()
plt.show()
plt.figure()
plt.loglog(refValues[:,0],refValue_Sigma,label="py")
plt.loglog((spc.speed_of_light*1e2)/(resultsLambda),resultsSigma,label="c++")
plt.legend()
plt.show()
plt.figure()
plt.loglog(refValues[:,0],refValue_E1)
plt.loglog((spc.speed_of_light*1e2)/(resultsLambda),resultsE1)
plt.show()
plt.figure()
plt.loglog(refValues[:,0],refValue_E2)
plt.loglog((spc.speed_of_light*1e2)/(resultsLambda),resultsE2)
plt.show()
 """
plt.figure()
plt.title(r"($\kappa$) comparison")
plt.xlabel(r"$\lambda$")
plt.ylabel(r"$\kappa$")
plt.loglog(refValues[:,0],refValues[:,1],label="Python")
plt.loglog((spc.speed_of_light*1e2)/(resultsLambda),resultsKappa,label="C++")
plt.legend()
plt.show()

#print(resultsNu)
#plt.figure()
#plt.loglog(refValues[:,0],refValues[:,1],label="Python")
#plt.loglog(resultsDustSize,resultsDust,label="C++")
#plt.legend()
#plt.show()


#print(resultsNu)
#plt.figure()
#plt.loglog(refValues[:,0],refValues[:,1],label="Python")
#plt.loglog(refValue_dustsize,refValue_dusts,label="C++")
#plt.legend()
#plt.show()


plt.figure()
plt.title(r"Re($\nu$) comparison")
plt.xlabel(r"$\lambda$")
plt.ylabel(r"Re($\nu$)")
plt.loglog(refValues[:,0],refValues_nu.real,label="Python")
plt.loglog(refValues[:,0],resultsNu.real,label="OpacityTools")
plt.legend()
plt.show()


plt.figure()
plt.title(r"Im($\nu$) comparison")
plt.xlabel(r"$\lambda$")
plt.ylabel(r"Im($\nu$)")
plt.loglog(refValues[:,0],refValues_nu.imag,label="Python")
plt.loglog(refValues[:,0],resultsNu.imag,label="OpacityTools")
plt.legend()
plt.show() 